#ifndef __ERROR_H
#define __ERROR_H

#define ERROR_INVALID_ARGUMENTS 1
#define ERROR_SCRIPT_FAILED_OPEN 2
#define ERROR_SCRIPT_EMPTY 4
#define ERROR_CONFIG_FAILED_OPEN 1024
#define ERROR_CONFIG_EMPTY 2048
#define ERROR_STAT 8
#define ERROR_NOTIFY_HANDLE 16
#define ERROR_WAIT_FAILED 32
#define ERROR_WAIT_ABANDONED 64
#define ERROR_FIND_NEXT 128
#define ERROR_RETRY_NOTIFY_WATCH 256
#define ERROR_LOG_FAILED 512
#define ERROR_STATUS_SHUTDOWN 8192

#endif
